MandatoryA/Areas/Admin/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MandatoryA.Infrastructure;
using MandatoryA.Controllers;
using MandatoryA.Models;

namespace MandatoryA.Areas.Admin.Controllers
{
    public class CustomersController : SessionController
    {
        // GET: Admin/Customers
        public ActionResult Index()
        {
            return View(SessionRepository);
        }
    }
}

MandatoryA/Areas/Admin/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MandatoryA.Infrastructure;
using MandatoryA.Controllers;
using MandatoryA.Models;

namespace MandatoryA.Areas.Admin.Controllers
{
    public class EmployeesController : SessionController
    {
        // GET: Admin/Employees
        public ActionResult Index()
        {
            
            return View(SessionRepository);
        }
        public ActionResult EditEmployee(int? id)
        {
            if (id != null)
            {
                Employee emp = (from s in SessionRepository.Employees where id == s.PersonID select s).Single();
                return View(emp);

            }
            else
            {
                return Content("No id");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditEmployee(Employee emp)
        {
            //int emp = 0;
            if(emp != null)
            {
                // Find index of employee personid and replace
                int index = SessionRepository.Employees.FindIndex(x => x.PersonID == emp.PersonID);
                SessionRepository.Employees[index] = emp;
                return View("Index", SessionRepository);
            }
            else
            {
                return Content("No employee");
            }
        }
        public ActionResult CreateEmployee()
        {
            // employee empty constructor doesnt update personid
            return View(new Employee());
        }
        [HttpPost]
        public ActionResult CreateEmployee(Employee emp)
        {
            // make an employee with person id autonum set in this employee constructor
           Employee employee = new Employee(emp.Firstname, emp.Lastname, emp.Initials, emp.Phone);
            // update employees list
            SessionRepository.Employees.Add(employee);
            return View("Index", SessionRepository);
        }
        public ActionResult DeleteEmployee(int? id)
        {
            if (id != null)
            {
                return View(SessionRepository.Employees.Single(x => x.PersonID == id));
            }
            else
            {
                return Content("No employee");
            }
            // employee empty constructor doesnt update personid
        }
        [HttpPost]
        public ActionResult DeleteEmployee(int id)
        {
            if (id != null)
            {
                // Find index of employee personid and delete
                int index = SessionRepository.Employees.FindIndex(x => x.PersonID == id);
                SessionRepository.Employees.RemoveAt(index);
                return View("Index", SessionRepository);
            }
            else
            {
                return Content("No employee");
            }
        }

    }

}

MandatoryA/Areas/Admin/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MandatoryA.Infrastructure;
using MandatoryA.Models;
using MandatoryA.Controllers;


namespace MandatoryA.Areas.Admin.Controllers
{
    public class InvoicesController : SessionController
    {
        // GET: Invoices
        public ActionResult Index()
        {
            return View(SessionRepository);
        }
        [HttpGet]
        public ActionResult Invoice(int? id)
        {
            if (id != null)
            {
                //Show all reservations
                //List<Reservation> customerReservations = SessionRepository.Reservations.FindAll(delegate (Reservation re) { return re.Customer.PersonID == id; });
                List<Reservation> customerReservations = SessionRepository.Reservations.FindAll(re=>re.Customer.PersonID == id );
                SessionRepository.Reservations[0].Customer.Firstname = "test";

                //Make selectlist with all customers - Linq dot notation
                SelectList customerList = new SelectList(SessionRepository.Reservations.Select(x => new { Name = x.Customer.Firstname + " " + x.Customer.Lastname, x.Customer.PersonID }).Distinct(), "PersonID", "Name");
                ViewBag.customerList = customerList;
                 
                // make a generic datatype, strongly typed
                Tuple<List<Reservation>, Repository> modelData = Tuple.Create(customerReservations, SessionRepository);

                return View(modelData);
            }
            return Content("No Content - No ID");
        }
    }
}

MandatoryA/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MandatoryA.Infrastructure;
using MandatoryA.Models;

namespace MandatoryA.Controllers
{
    public class ReservationsController : SessionController
    {
        // GET: reservations
        public ActionResult Index()
        {
            return View(SessionRepository);
        }

        
        public ActionResult CreateReservation()
        {
            // best solution for posting data from forms
            //ViewmodelReservation vm = new ViewmodelReservation{ Repository = SessionRepository };
            ViewBag.employeesList = new SelectList(from s in SessionRepository.Employees select new { PersonID = s.PersonID, Name = s.Firstname + " " + s.Lastname }, "PersonID", "Name");

             ViewBag.specieList = new SelectList( SessionRepository.Prices, "Key","Key");

            ViewBag.prices = SessionRepository.Prices;
            return View(new Reservation());
            //return View(Tuple.Create(new Reservation(),SessionRepository, new Customer()));
        }

        // CSRF 
        [HttpPost][ValidateAntiForgeryToken]
        public ActionResult CreateReservation(Reservation res)
        {
            // update employee to personid and create customer from form
            res.Employee = (Employee)(from s in SessionRepository.Employees where s.PersonID == res.EmployeeID select s).Single();
            res.Customer = new Customer(res.Firstname,res.Lastname,res.Address,res.Zipcode,res.City, res.Email, res.Phone);
            // add reservation and customer to sessionrepository
            SessionRepository.Reservations.Add(res);
            SessionRepository.Customers.Add(res.Customer);
            return View("Reservation", Tuple.Create(res, SessionRepository));
        }

    }
}

MandatoryA/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pet Hotel</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body style="background-color:cornflowerblue;">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button><span>
                    <img src="~/Content/white-shark2.jpg" class="img-responsive img-circle pull-left" style="width:75px; margin:5px;" />
                    @Html.ActionLink("Pet Hotel - we never bite Admin", "Index", "Home", new { area = "" }, new { @class = "navbar-brand myheader" })
                </span>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("List Invoices", "Index", "Invoices", null, new { @class = "reservation" })</li>
                    <li>@Html.ActionLink("List Reservations", "Index", "Reservations", null, new { @class = "reservation" })</li>
                    <li>@Html.ActionLink("List Customers", "Index", "Customers", null, new { @class = "reservation" })</li>
                    <li>@Html.ActionLink("List Employees", "Index", "Employees", null, new { @class = "reservation" })</li>
</ul>
                <ul class="nav navbar-nav navbar-right">
                   
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>


    <div class="container body-content" style="padding-top:80px;">
        <div class="row">
            <div id="main-content" class="jumbotron col-md-12">
                @RenderBody()
            </div>

            <div id="info-boxes" class="col-md-3">
                @RenderSection("Contact", false)
                @RenderSection("Pricelist", false)
                @* the false parameter here means that the section IS NOT REQUIRED
                    to be defined for a given view, but if IT IS DEFINED then it will
                    be rendered here and using the css defined under the id "info-boxes"*@
            </div>
        </div>
        <footer>
            <hr />

            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>