MandatoryA/Areas/Admin/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MandatoryA.Areas.Admin.Controllers
{
    public class AdminHomeController : Controller
    {
        // GET: Admin/AdminHome
        public ActionResult Index()
        {
            return View();
        }
    }
}

MandatoryA/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MandatoryA.Infrastructure;
using MandatoryA.Models;

namespace MandatoryA.Controllers
{
    public class ReservationsController : SessionController
    {
        // GET: reservations
        public ActionResult Index()
        {
            return View(SessionRepository);
        }

        
        public ActionResult CreateReservation()
        {
            // best solution for posting data from forms
            //ViewmodelReservation vm = new ViewmodelReservation{ Repository = SessionRepository };
            ViewBag.employeesList = new SelectList(from s in SessionRepository.Employees select new { PersonID = s.PersonID, Name = s.Firstname + " " + s.Lastname }, "PersonID", "Name");

             ViewBag.specieList = new SelectList( SessionRepository.Prices, "Key","Key");

            ViewBag.prices = SessionRepository.Prices;
            return View(new Reservation());
            //return View(Tuple.Create(new Reservation(),SessionRepository, new Customer()));
        }

        // CSRF 
        [HttpPost][ValidateAntiForgeryToken]
        public ActionResult CreateReservation(Reservation res)
        {
            // update employee to personid and create customer from form
            res.Employee = (Employee)(from s in SessionRepository.Employees where s.PersonID == res.EmployeeID select s).Single();
            res.Customer = new Customer(res.Firstname,res.Lastname,res.Address,res.Zipcode,res.City, res.Email, res.Phone);
            // add reservation and customer to sessionrepository
            SessionRepository.Reservations.Add(res);
            SessionRepository.Customers.Add(res.Customer);
            return View("Reservation", Tuple.Create(res, SessionRepository));
        }

    }
}

MandatoryA/Views/Shared/_ContactInfo.cshtml
@{
    Layout=null;
}

@* This is a partiel view. It is NOT strongly typed, because there is no
    model specified here. *@

<div id="contact-info" class="container well">
    <p><span class="small-caps">Location</span><br />
    Dyrevensvej 33<br />
    8000 Aarhus C<br />
    MAP 
</p>
    <p><span class="small-caps">Hours</span><br />
    M-F 8am-6pm<br />
    Saturday 8am-2pm<br />
    Sunday 12pm-5pm
</p>
</div>
 

MandatoryA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pet Hotel</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button><span>
    <img src="~/Content/white-shark2.jpg" class="img-responsive img-circle pull-left" style="width:75px; margin:5px;"/>
    @Html.ActionLink("Pet Hotel - we never bite", "Index", "Home", new { area = "" }, new { @class = "navbar-brand myheader" })
</span>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home","Index", "Home", new { area = "" }, null)</li>
                    <li><a href="#contact">Contact</a></li>
                    <li><a href="#contact">Services</a></li>
                    <li>@Html.ActionLink("Reservation", "CreateReservation", "Reservations", new { area = "" }, new { @class = "reservation" })</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="active">@Html.ActionLink("Administration Area", "Index", "AdminHome", new { area = "Admin" }, new { @class = "adminmenu" })</li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    

    <div class="container body-content">
        <div class="row">
            <div id="main-content" class="col-md-9">
                @RenderBody()
            </div>

            <div id="info-boxes" class="col-md-3">
                @RenderSection("Contact", false)
                @RenderSection("Pricelist", false)
                @* the false parameter here means that the section IS NOT REQUIRED
                to be defined for a given view, but if IT IS DEFINED then it will
                be rendered here and using the css defined under the id "info-boxes"*@
            </div>
        </div>
        <footer>
            <hr />

            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

MandatoryA/Views/Shared/_Pricelist.cshtml
@model Dictionary<string,int>

@{
    Layout = null;   
}
<div id="pricelist" class="container well">
    <h3>Prices</h3>
    <ul class="list-group">
        @foreach (var kvp in Model) {
            <li class="list-group-item">@kvp.Key @kvp.Value.ToString("N") kr.</li>

        }
    </ul>

</div>